export const RequirementToU = "terms-of-use"
export const RequirementImpressoAccount = "impresso-account"
export const RequirementProofStudentEnrollment = "proof-of-student-enrollment"
export const RequirementProofAcademicAffiliation =
  "proof-of-academic-affiliation"
export const RequirementDataAccessGranted = "data-access-granted"

export const Requirements: string[] = [
  RequirementToU,
  RequirementImpressoAccount,
  RequirementProofStudentEnrollment,
  RequirementProofAcademicAffiliation,
  RequirementDataAccessGranted,
]

export const RequirementsLabels: Record<string, string> = {
  [RequirementToU]: "Agreement to Terms of Use",
  [RequirementImpressoAccount]: "Creation of an Impresso Account",
  [RequirementProofStudentEnrollment]:
    "Proof of current student enrollment in higher education",
  [RequirementProofAcademicAffiliation]: "Proof of academic affiliation",
  [RequirementDataAccessGranted]:
    "Data access requires approval by content provider",
}

export const GenericFeatureExploreAll = "explore-all-features"
export const GenericFeatureCreateStoreExportCollections =
  "create-store-export-collections"
export const GenericFeatureGenerateApiKeys = "generate-api-keys"

export const GenericFeatures: string[] = [
  GenericFeatureExploreAll,
  GenericFeatureCreateStoreExportCollections,
  GenericFeatureGenerateApiKeys,
]

export const GenericFeatureLabels: Record<string, string> = {
  [GenericFeatureExploreAll]:
    "Explore all features of the Impresso Web App and Datalab.",
  [GenericFeatureCreateStoreExportCollections]:
    "Create, store and export personal collections.",
  [GenericFeatureGenerateApiKeys]:
    "Generate API keys to access parts of our corpus via the Impresso Datalab.",
}
export const DataFeatureMetadata = "metadata"
export const DataFeatureFacsimiles = "facsimiles"
export const DataFeatureAudio = "audio"
export const DataFeatureTranscripts = "transcripts"
export const DataFeatureImages = "images"
export const DataFeatureSemanticEnrichments = "semantic-enrichments"

export const DataFeatures: string[] = [
  DataFeatureMetadata,
  DataFeatureFacsimiles,
  DataFeatureAudio,
  DataFeatureTranscripts,
  DataFeatureImages,
  DataFeatureSemanticEnrichments,
]

export const DataFeatureLabels: Record<string, string> = {
  [DataFeatureMetadata]: "Bibliographic Metadata",
  [DataFeatureFacsimiles]:
    "Facsimiles - images of documents created during scanning",
  [DataFeatureAudio]: "Audio - mostly spoken word radio, mostly no music",
  [DataFeatureTranscripts]: "Transcripts - e.g. radio speaker notes",
  [DataFeatureImages]:
    "Images - e.g. those published by newspapers or radio magazines.",
  [DataFeatureSemanticEnrichments]:
    "Semantic enrichments generated by Impresso, e.g. named entities, text reuse clusters, topics, image classification etc.",
}

export const Features: string[] = [...GenericFeatures, ...DataFeatures]

export const PlanGuest = "guest"
export const PlanImpressoUser = "impresso-user"
export const PlanStudentUser = "student-user"
export const PlanAcademicUser = "academic-user"
export const PlanAcademicUserPlus = "academic-user-plus"
export const PlanLabels: Record<string, string> = {
  [PlanGuest]: "Guest",
  [PlanImpressoUser]: "No academic affiliation",
  [PlanStudentUser]: "Student",
  [PlanAcademicUser]: "Academic",
  [PlanAcademicUserPlus]: "Academic User Plus",
}

export const BrowserViewLogin = "login"
export const BrowserViewRegister = "signup"

export const BrowserViews: string[] = [BrowserViewLogin, BrowserViewRegister]

export const BrowserWsStatusIdle = "idle"
export const BrowserWsStatusConnecting = "connecting"
export const BrowserWsStatusConnected = "connected"
export const BrowserWsStatusClosed = "closed"

export const AccessTokenKey = "feathers-jwt"
export const BrowserWsStatuses: string[] = [
  BrowserWsStatusIdle,
  BrowserWsStatusConnecting,
  BrowserWsStatusConnected,
  BrowserWsStatusClosed,
]
