name: Update Notebooks if needed
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  updateNotebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Notebooks
        run: |
          python updateNotebooks.py
