name: Update Notebooks if needed
on:
  workflow_dispatch:

jobs:
  updateNotebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Update Notebooks
        run: node updatenotebooks.js
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
